-- Create the DEPARTMENT table if it does not exist
CREATE TABLE IF NOT EXISTS DEPARTMENT (
EMPLOYEE_ID TEXT,
NAME TEXT,
DEPARTMENT_ID TEXT,
MANAGER_ID TEXT,
SALARY RELEASE
);

--Insert sample data into the DEPARTMENT table
INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
('100','STEVEN KING','90','100', 24000),
('101','NEENA KOCCHAR','90','100', 17000),
('102','LEX DEHAAN','90','102', 9000),
('103','BRUCE LEE','60','103', 4800),
('104','DIANA WILLS','60','103', 25000),
('105','VALLI PATOR','50','100', 4200),
('1973','LUV HAMI','60','102',5000),
('106','DAVID AUSTIN','90','100',6000);

SELECT * FROM DEPARTMENT;
 
 --Query to count the number of employees in each department
 SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
 COUNT(*) AS "NO OF EMPLOYEES"
 FROM DEPARTMENT
 GROUP BY DEPARTMENT_ID;

 --sum of salary--

 SELECT DEPARTMENT_ID, SUM(SALARY)
 FROM DEPARTMENT
 GROUP BY DEPARTMENT_ID;

 SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
 SUM(SALARY) AS "TOTAL SALARY"
 FROM DEPARTMENT
 WHERE MANAGER_ID = '103'
 GROUP BY DEPARTMENT_ID;

 -- Query to find department with more than 2 employess

 SELECT DEPARTMENT_ID, COUNT(*) AS "NO. of Employees"
 FROM DEPARTMENT
 GROUP BY DEPARTMENT_ID
 HAVING COUNT(*) > 2;
