-- Create the NOBEL_WIN table if it does not exist
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

--Insert sample data into the NOBEL_WIN table
INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970, 'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
(1970, 'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
(1971, 'PHYSICS','PAUL','FRANCE','SCIENTIST'),
(1971, 'CHEMISTRY','HAMILTON','SWEDEN','LINGUIST'),
(1972, 'LITERATURE','BERNARD KELSON','GERMANY','ECONOMIST'),
(1972, 'ECONOMICS','PHILIPS','USA','PRIME MINISTER'),
(1980, 'BIOLOGY','MARTIN','USA','PRESIDENT'),
(1981, 'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1975, 'PYHSICS','PETER','CHILE','SCIENTIST');

SELECT * FROM NOBEL_WIN;

SELECT * FROM NOBEL_WIN WHERE SUBJECT = 'PHYSICS';


SELECT * FROM NOBEL_WIN WHERE CATEGORY = 'SCIENTIST';

SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE 'P%';

SELECT * FROM NOBEL_WIN ORDER BY YEAR DESC, WINNER ASC;